version = 0.1

[default.deploy.parameters]
stack_name = "trading-journal-backend"
resolve_s3 = true
s3_prefix = "trading-journal-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\" ApiVersion=\"v1\" GeminiApiKey=\"/trading-journal/geminiApiKey\""
image_repositories = []
