version = 0.1

[default.deploy.parameters]
stack_name = "tradeflow-dev"
resolve_s3 = true
s3_prefix = "trading-journal-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"tradeflow-dev\" ApiVersion=\"v1\" GeminiApiKeyParamName=\"/tradeflow/geminiApiKey\""
image_repositories = []
